SaudePublica/Saude/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using Saude.Controllers.Attributes;
using Saude.Models.Enums;

namespace Saude.Controllers
{
	[AuthorizeByPerfil(PerfilAcessoEnum.Admin, PerfilAcessoEnum.Paciente)]
	public class PacienteController : Controller
	{
		public IActionResult AreaPaciente()
		{
			return View();
		}
	}
}

SaudePublica/Saude/Controllers/PerfilAcessoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Saude.Controllers.Attributes;
using Saude.Models.Context;
using Saude.Models.Entity;
using Saude.Models.Enums;
using Saude.Services;

namespace Saude.Controllers
{
	[AuthorizeByPerfil(PerfilAcessoEnum.Admin)]
    public class PerfilAcessoController : Controller
    {
        private readonly PerfilAcessoService _perfilAcessoService;

        public PerfilAcessoController(SaudeDbContext context)
        {
            _perfilAcessoService = new PerfilAcessoService(context);
        }

        // GET: PerfilAcesso
        public async Task<IActionResult> Index()
        {
            return View(_perfilAcessoService.GetAllPerfilAcesso());
        }

        // GET: PerfilAcesso/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Perfil_Acesso perfil_Acesso = _perfilAcessoService.GetPerfilAcesso(id.Value);
            if (perfil_Acesso == null)
            {
                return NotFound();
            }

            return View(perfil_Acesso);
        }

        // GET: PerfilAcesso/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PerfilAcesso/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Perfil_Acesso perfil_Acesso)
        {
            if (ModelState.IsValid)
            {
                _perfilAcessoService.AddPerfilAcesso(perfil_Acesso);
                return RedirectToAction(nameof(Index));
            }
            return View(perfil_Acesso);
        }

        // GET: PerfilAcesso/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfil_Acesso = _perfilAcessoService.GetPerfilAcesso(id.Value) ;
            if (perfil_Acesso == null)
            {
                return NotFound();
            }
            return View(perfil_Acesso);
        }

        // POST: PerfilAcesso/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Perfil_Acesso perfil_Acesso)
        {
            if (id != perfil_Acesso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _perfilAcessoService.UpdatePerfilAcesso(perfil_Acesso);
                return RedirectToAction(nameof(Index));
            }
            return View(perfil_Acesso);
        }

        // GET: PerfilAcesso/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Perfil_Acesso perfil_Acesso = _perfilAcessoService.GetPerfilAcesso(id.Value);
            if (perfil_Acesso == null)
            {
                return NotFound();
            }

            return View(perfil_Acesso);
        }

        // POST: PerfilAcesso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _perfilAcessoService.DeletePerfilAcesso(id);
            return RedirectToAction(nameof(Index));
        }
    }

}

SaudePublica/Saude/Controllers/TipoExameMedicoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Saude.Controllers.Attributes;
using Saude.Models.Context;
using Saude.Models.Entity;
using Saude.Models.Enums;
using Saude.Services;

namespace Saude.Controllers
{
	[AuthorizeByPerfil(PerfilAcessoEnum.Admin)]
	public class TipoExameMedicoController : Controller
	{
		private readonly TipoExameMedicoService _service;

		public TipoExameMedicoController(SaudeDbContext context)
		{
			_service = new TipoExameMedicoService(context);
		}

		// GET: TipoExameMedico
		public async Task<IActionResult> Index()
		{
			return View(_service.GetAllTipoExameMedico());
		}

		// GET: TipoExameMedico/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Tipo_Exame_Medico tipoExameMedico = _service.GetTipoExameMedico(id.Value);
			if (tipoExameMedico == null)
			{
				return NotFound();
			}

			return View(tipoExameMedico);
		}

		// GET: TipoExameMedico/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: TipoExameMedico/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Nome,Descricao")] Tipo_Exame_Medico tipoExameMedico)
		{
			this.CustomValidationTipoExameMedico(tipoExameMedico);
			if (ModelState.IsValid)
			{
				_service.AddTipoExameMedico(tipoExameMedico);
				return RedirectToAction(nameof(Index));
			}

			return View(tipoExameMedico);
		}

		// GET: TipoExameMedico/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Tipo_Exame_Medico tipoExameMedico = _service.GetTipoExameMedico(id.Value);
			if (tipoExameMedico == null)
			{
				return NotFound();
			}

			return View(tipoExameMedico);
		}

		// POST: TipoExameMedico/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao")] Tipo_Exame_Medico tipoExameMedico)
		{
			if (id != tipoExameMedico.Id)
			{
				return NotFound();
			}

			this.CustomValidationTipoExameMedico(tipoExameMedico);
			if (ModelState.IsValid)
			{
				_service.UpdateTipoExameMedico(tipoExameMedico);
				return RedirectToAction(nameof(Index));
			}

			return View(tipoExameMedico);
		}

		// GET: TipoExameMedico/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Tipo_Exame_Medico tipoExameMedico = _service.GetTipoExameMedico(id.Value);
			if (tipoExameMedico == null)
			{
				return NotFound();
			}

			return View(tipoExameMedico);
		}

		// POST: TipoExameMedico/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			_service.DeleteTipoExameMedico(id);
			return RedirectToAction(nameof(Index));
		}

		private void CustomValidationTipoExameMedico(Tipo_Exame_Medico tipoExameMedico)
		{
			if (_service.ExistsTipoExameMedico(tipoExameMedico))
			{
				ModelState.AddModelError("Tipo_Exame_Medico", "Já existe um tipo de exame médico cadastrado com esse nome.");
			}
		}
	}
}

SaudePublica/Saude/Controllers/UsuarioController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Saude.Controllers.Attributes;
using Saude.Models.Context;
using Saude.Models.Entity;
using Saude.Models.Enums;
using Saude.Models.ViewModel;
using Saude.Services;

namespace Saude.Controllers
{
	[AuthorizeByPerfil(PerfilAcessoEnum.Admin, PerfilAcessoEnum.Paciente)]
    public class UsuarioController : Controller
    {
        private readonly UsuarioService _usuarioService;
        private readonly PerfilAcessoService _perfilAcessoService;
        private readonly TipoCargoProfissionalSaudeService _tipoCargoProfissionalSaudeService;

        public UsuarioController(SaudeDbContext context)
        {
            _usuarioService = new UsuarioService(context);
            _perfilAcessoService = new PerfilAcessoService(context);
            _tipoCargoProfissionalSaudeService = new TipoCargoProfissionalSaudeService(context);
        }

        // GET: Usuario
        public async Task<IActionResult> Index()
        {
            return View(_usuarioService.GetAllUsuarioList());
        }

        // GET: Usuario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _usuarioService.GetUsuario(id.Value);
            if (usuario == null)
            {
                return NotFound();
            }

            UsuarioViewModel viewModel = _usuarioService.UsuarioToViewModel(usuario);
            return View(viewModel);
        }

        // GET: Usuario/Create
        public IActionResult Create()
        {
	        this.SetDropdownListToViewBag();
            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UsuarioViewModel usuario)
        {
	        this.CustomValidationUsuarioViewModel(usuario);
	        if (ModelState.IsValid)
	        {
		        _usuarioService.CreateUsuario(usuario);

                if(((ClaimsIdentity)User.Identity).HasClaim(ClaimTypes.Role, ((int)PerfilAcessoEnum.Admin).ToString()))
                {
	                return RedirectToAction("Index");
                }

                string message = $"Login {usuario.Login} criado com sucesso. Utilize a seção de login para entrar no sistema.";
                return RedirectToAction("Index", "Home", new { Message = message });
	        }

	        this.SetDropdownListToViewBag();
	        return View(usuario);
        }

        [AllowAnonymous]
        // GET: Usuario/Register
        public IActionResult Register([Bind("Nome,Login")] UsuarioViewModel usuario)
        {
	        this.SetDropdownListToViewBag();
            ModelState.Clear();
            return View(nameof(Create), usuario);
        }

        // GET: Usuario/CreateAdmin
        public IActionResult CreateAdmin()
        {
	        return View();
        }

        // POST: Usuario/CreateAdmin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAdmin([Bind("Login,Senha")] Usuario usuario)
        {
	        this.CustomValidationUsuarioAdmin(usuario);
	        if (ModelState.IsValid)
	        {
		        _usuarioService.CreateUsuarioAdmin(usuario);
		        return RedirectToAction(nameof(Index));
	        }

	        return View(usuario);
        }


        // GET: Usuario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
	        if (id == null)
	        {
		        return NotFound();
	        }

	        Usuario usuario = _usuarioService.GetUsuario(id.Value);
	        if (usuario == null)
	        {
		        return NotFound();
	        }

	        UsuarioViewModel viewModel = _usuarioService.UsuarioToViewModel(usuario);
	        this.SetDropdownListToViewBag();

	        return View(viewModel);
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UsuarioViewModel usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            this.CustomValidationUsuarioViewModel(usuario);
            if (ModelState.IsValid)
            {
                _usuarioService.UpdateUsuario(usuario);
                return RedirectToAction(nameof(Index));
            }

            this.SetDropdownListToViewBag();
            return View(usuario);
        }

        // GET: Usuario/EditAdmin/5
        public async Task<IActionResult> EditAdmin(int? id)
        {
	        if (id == null)
	        {
		        return NotFound();
	        }

	        Usuario usuario = _usuarioService.GetUsuario(id.Value);
	        if (usuario == null)
	        {
		        return NotFound();
	        }

	        return View(usuario);
        }

        // POST: Usuario/EditAdmin/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAdmin(int id, Usuario usuario)
        {
	        if (id != usuario.Id)
	        {
		        return NotFound();
	        }

	        this.CustomValidationUsuarioAdmin(usuario);
	        if (ModelState.IsValid)
	        {
		        _usuarioService.UpdateUsuarioAdmin(usuario);
		        return RedirectToAction(nameof(Index));
	        }

	        this.SetDropdownListToViewBag();
	        return View(usuario);
        }

        // GET: Usuario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Usuario usuario = _usuarioService.GetUsuario(id.Value);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(_usuarioService.UsuarioToViewModel(usuario));
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
			_usuarioService.DeleteUsuario(id);
            return RedirectToAction(nameof(Index));
        }

        private void SetDropdownListToViewBag()
        {
	        ViewBag.PerfilAcessoList = _perfilAcessoService.GetAllPerfilAcessoAllowedForRegister().Select(x =>
		        new SelectListItem
		        {
			        Text = x.Nome,
			        Value = x.Id.ToString()
		        }).ToList();

	        ViewBag.TipoCargoProfissionalSaudeList = _tipoCargoProfissionalSaudeService.GetAllTipoCargoProfissionalSaude()
		        .Select(x => new SelectListItem
		        {
			        Text = x.Nome,
			        Value = x.Id.ToString()
		        }).ToList();
        }


        private void CustomValidationUsuarioViewModel(UsuarioViewModel usuario)
        {
	        if (usuario.Perfil_Acesso_Id == PerfilAcessoEnum.ProfissionalSaude &&
	            usuario.Tipo_Cargo_Profissional_Saude.HasValue == false)
	        {
		        ModelState.AddModelError("Tipo_Cargo_Profissional_Saude",
			        "Tipo de cargo do profissional de saúde é obrigatório para esse perfil.");
	        }

	        if (_usuarioService.ExisteOutroUsuarioJaCadastrado(usuario))
	        {
		        ModelState.AddModelError("Model",
			        "Login ou Cpf já cadastrados, por favor verifique os campos de cadastro ou efetue login com suas credenciais.");
	        }
        }

        private void CustomValidationUsuarioAdmin(Usuario usuario)
        {
	        if (_usuarioService.ExisteMesmoLoginJaCadastrado(usuario))
	        {
		        ModelState.AddModelError("Model", "Login já em uso. Favor escolher um outro login");
	        }
        }

    }
}

SaudePublica/Saude/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Saude.Models.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Saude</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" aria-label="Home">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
	                @if (((System.Security.Claims.ClaimsIdentity) User.Identity).HasClaim(ClaimTypes.Role, ((int) PerfilAcessoEnum.Admin).ToString()))
	                {
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index" aria-label="Usuários">Usuários</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="PerfilAcesso" asp-action="Index" aria-label="Perfis de acesso">Perfis de Acesso</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="TipoExameMedico" asp-action="Index" aria-label="Tipos de exame">Tipos de Exame</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="TipoProcedimentoMedico" asp-action="Index" aria-label="Tipos de procedimentos médicos">Tipos de Procedimentos Médicos</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="TipoCargoProfissionalSaude" asp-action="Index" aria-label="Cargos de Prof. de Saúde">Cargos de Prof. de Saúde</a>
		                </li>
	                }
		                
	                @if (((ClaimsIdentity) User.Identity).HasClaim(ClaimTypes.Role, ((int) PerfilAcessoEnum.Admin).ToString())
					   || ((ClaimsIdentity)User.Identity).HasClaim(ClaimTypes.Role, ((int)PerfilAcessoEnum.ProfissionalSaude).ToString()))
					{
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="CodigoInternacionalDoencas" asp-action="Index" aria-label="Código de doenças">Código de Doenças</a>
		                </li>
	                }
                        
	                @if (((ClaimsIdentity) User.Identity).HasClaim(ClaimTypes.Role, ((int) PerfilAcessoEnum.Paciente).ToString()))
	                {
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="AreaPaciente" aria-label="Área do paciente">Área do Paciente</a>
		                </li>
	                }
                </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
	                <ul class="navbar-nav">
		                <li class="login-right">
			                @if (User.Identity.IsAuthenticated)
			                {
				                <div>
					                Olá @User.Identity.Name!
				                </div>
				                <a asp-controller="Login" asp-action="Logout" aria-label="Sair">Sair</a>
			                }

		                </li>
	                </ul>
					</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Sistema de Saúde - Renan Pereira Araújo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>